<?php
echo ceil(4.2);
echo '<br/>';
echo floor(4.9).'<br/>';
echo pow(-2,5).'<br/>';
echo round(1.88823,1).'<br/>';
echo sqrt(2).'<br/>';
echo max(1,4,5,4,5).'<br/>';
echo mt_rand(0,4).'<br/>';
echo pi().'<br/>';
echo trim('  12 34 5 ').'<br/>';
echo 'hello world '.'<br/>';
echo chop('111   ').'<br/>';
echo dirname('C://php-study/oop/index.php').'<br/>';
echo str_pad('hello php',10,'~').'<br/>';
echo str_repeat('.=',5).'<br/>';
var_dump(str_split('hello php',2));
echo join(',',['a','b','','c']).'<br/>';
echo strrev('abc').'<br/>';
$text  =  "The quick brown fox jumped over the lazy dog." ;
$newtext  =  wordwrap ( $text ,  20 ,  "<br/>" );
echo  wordwrap('hello php',1,'~');
echo '<br/>';
echo str_shuffle('hello php').'<br/>';
echo number_format(111123243234234,2,'.','~').'<br/>';
echo ucwords('hello php').'<br/>';
echo ucfirst('hello php').'<br/>';
echo ord('X').'<br/>';
echo strcmp('hello','HELLO').'<br/>';
$str = 'hello php';
$newstr = chunk_split($str,4,'~');
echo $newstr.'<br/>';
echo wordwrap($newstr,4,'~').'<br/>';
echo strtok('hello php','w');
var_dump(explode('&','hello&php&javascript&css'));
echo substr('hello php',2,2).'<br/>';
